version: '3'
services:
  vm0:
    hostname: vm0
    container_name: vm0
    image: consul-playground
    volumes:
      - .:/data/consul-playground
    networks:
      - main-network
    ports:
      - 8500:8500
  vm1:
    hostname: vm1
    container_name: vm1
    image: consul-playground
    volumes:
      - .:/data/consul-playground
    networks:
      - main-network
  vm2:
    hostname: vm2
    container_name: vm2
    image: consul-playground
    volumes:
      - .:/data/consul-playground
    networks:
      - main-network
  vm3:
    hostname: vm3
    container_name: vm3
    image: consul-playground
    volumes:
      - .:/data/consul-playground
    networks:
      - main-network

networks:
  main-network:
